givery-bootcamp/dena-2024-team2

- docker-compose.yml
- MySQLの立ち上げ時に、sqlファイルを実行するようにする
- MySQLに対してヘルスチェックを追加し、MySQLが立ち上がったのを確認してからバックエンドを起動する
> docker-composeの設定の修正

- .github/workflows/frontend.yaml
- biomeがgithub actions上で走査するディレクトリが変わってなかったので再度修正
- work_dirはあくまでlockファイルの走査対象だったみたい
> fix: biome target directory

- README.md
- api/api.yaml
- docker-compose.yml
- docker/apidoc-element.Dockerfile
- docker/resource/api-doc.html
APIドキュメントと、その閲覧環境を追加する
- `api/api.yaml`にAPIドキュメントを追加
- API Documentのビューアーとして`swagger-ui`及び`stoplight/element`をcomposeに追加
- mockとして`stoplight/prism`をcomposeに追加
- http://localhost:8000 にアクセスして、Swagger UIを閲覧できる
- http://localhost:8010 にアクセスして、Elementを閲覧できる
- http://localhost:8080 にアクセスして、レスポンスが返ってくる
> APIドキュメント閲覧環境の作成

- backend/internal/controllers/get_channel_controller.go
- backend/internal/middleware/router.go
取得したチャンネル一覧の構造体に JSON のプロパティマップを適用した。
Closes #33
- `localhost:9000/channel` で以下のように取得できる。
```
{
"channels":
[
{
"id":1,
"serverId":1,
"name":"channel1",
"createdAt":"2024-06-17T16:40:07+09:00",
"updatedAt":"2024-06-17T16:40:07+09:00",
"deletedAt":"0001-01-01T00:00:00Z"
},
{
"id":2,
"serverId":1,
"name":"channel2",
"createdAt":"2024-06-17T16:40:07+09:00",
"updatedAt":"2024-06-17T16:40:07+09:00",
"deletedAt":"0001-01-01T00:00:00Z"
}
]
}
```
> 取得したチャンネル一覧を JSON プロパティに変換する

- backend/internal/middleware/cors.go
- api通信の際に必要な設定が足りなかった（Auth Headerを追加したことにより足りなくなった）ので追加
- Credentials: include にしたらまたこの辺変更するかも…
> Backend側にcors用の設定を追加

- backend/internal/controllers/create_channel_controller.go
- backend/internal/entities/server.go
- backend/internal/interfaces/create_channel_repository.go
- backend/internal/interfaces/server_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/create_channel_repository.go
- backend/internal/repositories/server_repository.go
- backend/internal/usecases/create_channel_usecase.go
closes #45 
```
% curl -H POST 'localhost:9000/servers/1/channels' -H 'Content-Type: application/json' -d '{"name" : "channel3"}' -H 'Authorization: Bearer {{ TOKEN }}'
```
> {"id":3, "serverId":1, "name":"channel3", "createdAt":"2024-06-25T18:34:41.459+09:00"}
- `servers` テーブルに存在するのは、`1` の `serverId` のサーバー
- `channels` テーブルに存在するのは、`channel1` / `channel2` という `name` のチャンネル
- 別途、JWT を取得しておいてください
- `channel1` は重複しているのでエラーを返す
```
% curl -H POST 'localhost:9000/servers/1/channels' -H 'Content-Type: application/json' -d '{"name" : "channel1"}' -H 'Authorization: Bearer {{ TOKEN }}'
```
> {"message":"その名前はすでに使用されています。"}%
- `8` はテーブルに存在しないのでエラーを返す
```
% curl -H POST 'localhost:9000/servers/8/channels' -H 'Content-Type: application/json' -d '{"name" : "channel1"}' -H 'Authorization: Bearer {{ …
```
> チャンネルを作成する API の実装

- frontend/src/components/ui/index.ts
- frontend/src/components/ui/input/index.ts
- frontend/src/components/ui/input/input.module.scss
- frontend/src/components/ui/input/input.stories.tsx
- frontend/src/components/ui/input/input.tsx
- Inputコンポーネントを実装
- type=textのみ
close #54
> Frontend/#54 Inputコンポーネントの実装

- frontend/src/components/ui/index.ts
- frontend/src/components/ui/textarea/index.ts
- frontend/src/components/ui/textarea/textarea.module.scss
- frontend/src/components/ui/textarea/textarea.stories.tsx
- frontend/src/components/ui/textarea/textarea.tsx
- Textareaコンポーネントを実装
- 投稿作成用
- http://localhost:6001/?path=/docs/components-textarea--docs にアクセスする
- Textareaコンポーネントが表示される
- Textareaに文字が入力できる
- Placeholderの文字を変えると、コンポーネントにも反映される
close #55
> Frontend/#55 textareaコンポーネントの実装

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/model/server/index.ts
- frontend/src/components/model/server/server-list.module.scss
- frontend/src/components/model/server/server-list.stories.tsx
- frontend/src/components/model/server/server-list.tsx
- frontend/src/domains/servers/server.ts
- frontend/src/routeTree.gen.ts
- frontend/src/routes/server.$serverId_.channels.$channelId.lazy.tsx
- サーバーを一覧表示するコンポーネントを作成
- 追加用ボタンもとりあえず作ったが、処理が無いときは非表示にするようにした
- サーバーのtypeも作成した
- FEで取り回したいモデルとしてのtypeなので、req, resはAPI接続のとき別途作成
> Frontend/#11 サーバー一覧表示コンポーネントを作成

- frontend/src/components/model/channel/channel-list.module.scss
- frontend/src/components/model/channel/channel-list.stories.tsx
- frontend/src/components/model/channel/channel-list.tsx
- frontend/src/global.scss
> Frontend/#11 チャンネル一覧表示コンポーネントの実装

- backend/timeline/internal/config/config.go
- backend/timeline/internal/controllers/controller_helper.go
- backend/timeline/internal/infrastructures/jwt.go
- backend/timeline/internal/middleware/auth.go
- backend/timeline/internal/repositories/server_repository.go
- backend/timeline/internal/usecases/create_server_usecase.go
- docker-compose.yml
kotlinサーバーで発行されたjwtについても検証できるように修正した。
kotlinサーバーにsigninする
```
curl -X POST -H "Content-Type: application/json" -d '{"name":"ozaki","password":"password"}' http://localhost:9090/user/signin -c cookie.txt                                                                                                                                                                                                                       
```
→{"id":5,"name":"ozaki"}%     
cookie.txtに保存してあるjwtを使って、Authorizationヘッダーに貼り付ける
```
curl -X POST -H "Content-Type: application/json" -d '{"name":"name3","icon":"icon2"}' -H 'Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiaXNzIjoiS29kZWUiLCJpYXQiOjE3MTk0NjMxMDIsImV4cCI6MTcxOTQ2NjcwMiwidXNlcm5hbWUiOiJvemFraSJ9.kQeOesf2zxXI4qqRH9eDY244N-8diEjVkwP7tULN8 …
```
> userサーバーで発行されたjwtを検証&利用できるように認証の処理を修正した

- frontend/package-lock.json
- frontend/package.json
- frontend/src/utils/date-utils/date-utils.test.ts
- frontend/src/utils/date-utils/date-utils.ts
- frontend/src/utils/date-utils/index.ts
- 日時系の処理をまとめた date-utilsを作成
- 今回は一旦formatのみを実装
- date-fnsを使った
```
$ docker compose exec frontend npm run test
```
> Frontend/#79 date-utilsの実装

- backend/timeline/internal/controllers/create_channel_controller.go
- backend/timeline/internal/middleware/router.go
**前提：サインインして jwt をコピーしておく**
```
curl -H POST 'localhost:9000/servers/1/channels' -H 'Content-Type: application/json' -d '{"name" : "channel3"}' -b "training-jwt=<<トークン>>"
```
レスポンス
```
{"id":3,"serverId":1,"name":"channel3","createdAt":"2024-06-27T17:04:14.444+09:00"}% 
```
```
% docker-compose exec db mysql training
```
```
mysql> select * from channels;
+----+-----------+----------+---------------------+---------------------+------------+
| id | server_id | name     | created_at          | updated_at          | deleted_at |
+----+-----------+----------+---------------------+---------------------+------------+
|  1 |         1 | channel1 | 2024-06-27 11:30:19 | 2024-06-27 11:30:19 | NULL       |
|  2 |         1 | channel2 | 2024-06-27 11:30:19 | 2024-06-27 11:30:19 | NULL       |
|  3 | …
```
> チャンネルを作成する API の id のアップデート

- frontend/src/components/model/posts/index.ts
- frontend/src/components/model/posts/post-list.module.scss
- frontend/src/components/model/posts/post-list.stories.tsx
- frontend/src/components/model/posts/post-list.tsx
> Frontend/#11 投稿一覧コンポーネントの作成

- frontend/src/components/model/channel/channel-list.module.scss
- frontend/src/components/model/server/server-list.module.scss
- listの左にブラウザ標準のpaddingがついていたので削除
> listについてるpaddingを削除

- backend/timeline/internal/controllers/create_post_controller.go
- backend/timeline/internal/interfaces/channel_repository.go
- backend/timeline/internal/middleware/router.go
- backend/timeline/internal/usecases/create_post_usercase.go
closes #62 
- 投稿を作成する API の改修：`/servers/:serverId/channels/:channelId/posts`
- create_repository.go の interfaces を流れで作りました。
- 若干、この PR とズレちゃうけど。
**前提：サインインして jwt をコピーしておく**
```
curl -H POST 'localhost:9000/servers/1/channels/1/posts' -H 'Content-Type: application/json' -d '{"user_id": 1, "content" : "ワイワイ"}' -b "training-jwt=<<トークン>>"
```
レスポンス
```
{"id":3,"channel_id":1,"User":{"Id":1,"Name":""},"content":"ワイワイ","created_at":"2024-06-28T11:06:23.33+09:00","updated_at":"2024-06-28T11:06:23.33+09:00","deleted_at":null}
```
```
% docker-compose exec db mysql training
```
```
mysql> select * from posts;
+----+---------+------------+----------------+---------------------+---------------------+------------+
| id | user_id | channel_id | content        | created_at          | updated_at …
```
> 投稿を作成する API の改修

- frontend/src/components/page/index.ts
- frontend/src/components/page/servers/index.ts
- frontend/src/components/page/servers/mock.ts
- frontend/src/components/page/servers/servers.module.scss
- frontend/src/components/page/servers/servers.tsx
- frontend/src/routeTree.gen.ts
- frontend/src/routes/servers.lazy.tsx
- frontend/src/routes/spaces.$spaceId.lazy.tsx
- サーバー一覧ページのUIを作成
- APIの接続は別PR
> Frontend/#95 サーバー一覧ページのUIを作成

- backend/timeline/internal/controllers/controller_helper.go
- backend/timeline/internal/controllers/create_post_controller.go
- backend/timeline/internal/infrastructures/jwt.go
- backend/timeline/internal/interfaces/create_post_repository.go
- backend/timeline/internal/middleware/auth.go
- backend/timeline/internal/repositories/create_post_repository.go
- backend/timeline/internal/usecases/create_post_usercase.go
closes #92 
- user_id と user_name を jwt から取得するようにした
- レスポンスの形式を投稿取得 API と揃えるように controller.go で関数を追加した
```
% curl -H POST 'localhost:9000/servers/1/channels/1/posts' -H 'Content-Type: application/json' -d '{"content" : "ワイワイ"}' -b "training-jwt=<<トークン>>"
```
```
{
"id":17,
"channel_id":1,
"user_id":4,
"user_name":"Takanori",
"content":"ワイワイ",
"created_at":"2024-06-28T15:00:28.859+09:00"
}
```
> 投稿作成 API：ユーザー情報を jwt から取得する

- backend/user/src/main/kotlin/myapp/plugins/Routing.kt
- cookieの有効範囲（path）が指定されてなかったので指定
> cookieをフロント側で取り回すための設定を追加

- .env.sample
- frontend/.env.production
- frontend/src/components/page/servers/servers.tsx
- frontend/src/domains/channels/get-channels.ts
- frontend/src/domains/servers/get-servers.ts
- frontend/src/domains/servers/index.ts
> Frontend/#95 サーバー一覧画面のAPI接続

- frontend/src/components/model/server/server-list.module.scss
- frontend/src/components/model/server/server-list.tsx
- ログイン〜投稿一覧までを画面ぽちぽちでいけるように
close #108
> Frontend/#108 ログイン〜投稿一覧までの流れを作る
